# Case change

print('================================')
print('         Case change')
print('================================')

x = str(input('Enter a letter : '))

if x == str('a'): nw = str('A')
elif x == str('b'): nw = str('B')
elif x == str('c'): nw = str('C')
elif x == str('d'): nw = str('D')
elif x == str('e'): nw = str('E')
elif x == str('f'): nw = str('F')
elif x == str('g'): nw = str('G')
elif x == str('h'): nw = str('H')
elif x == str('i'): nw = str('I')
elif x == str('j'): nw = str('J')
elif x == str('k'): nw = str('K')
elif x == str('l'): nw = str('L')
elif x == str('m'): nw = str('M')
elif x == str('n'): nw = str('N')
elif x == str('o'): nw = str('O')
elif x == str('p'): nw = str('P')
elif x == str('q'): nw = str('Q')
elif x == str('r'): nw = str('R')
elif x == str('s'): nw = str('S')
elif x == str('t'): nw = str('T')
elif x == str('u'): nw = str('U')
elif x == str('v'): nw = str('V')
elif x == str('w'): nw = str('W')
elif x == str('x'): nw = str('X')
elif x == str('y'): nw = str('Y')
elif x == str('z'): nw = str('Z')
elif x == str('A'): nw = str('a')
elif x == str('B'): nw = str('b')
elif x == str('C'): nw = str('c')
elif x == str('D'): nw = str('d')
elif x == str('E'): nw = str('e')
elif x == str('F'): nw = str('f')
elif x == str('G'): nw = str('g')
elif x == str('H'): nw = str('h')
elif x == str('I'): nw = str('i')
elif x == str('J'): nw = str('j')
elif x == str('K'): nw = str('k')
elif x == str('L'): nw = str('l')
elif x == str('M'): nw = str('m')
elif x == str('N'): nw = str('n')
elif x == str('O'): nw = str('o')
elif x == str('P'): nw = str('p')
elif x == str('Q'): nw = str('q')
elif x == str('R'): nw = str('r')
elif x == str('S'): nw = str('s')
elif x == str('T'): nw = str('t')
elif x == str('U'): nw = str('u')
elif x == str('V'): nw = str('v')
elif x == str('W'): nw = str('w')
elif x == str('X'): nw = str('x')
elif x == str('Y'): nw = str('y')
else: nw = str('z')

print('\t:', nw)

# Ravindu Rasanjana Herath
# E/23/147